#:schema node_modules/wrangler/config-schema.json
name = "actions-public-oidc"
main = "src/index.ts"
compatibility_date = "2024-09-29"
routes = [
  { pattern = "actions-public-oidc.depot.dev/*", zone_name = "depot.dev" },
]

kv_namespaces = [
  { binding = "KEYS", id = "27f275addb7b4bd9bf3f34b7977948d4", preview_id = "a9e6dd26d0764ba8b8ed2ba00d035efe" },
]

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "CLAIM", class_name = "Claim" },
  { name = "WATCHER", class_name = "Watcher" },
]

[[migrations]]
tag = "v1"
new_classes = ["Claim"]

[[migrations]]
tag = "v2"
new_classes = ["Watcher"]
