name: rotate-keys
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 1,15 * *' # 12:00 on the 1st and 15th of every month

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | sh

      - name: Rotate keys
        run: |
          sentry-cli monitors run actions-public-oidc-rotate-keys -- ./support/rotate-keys.sh
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
