on:
  workflow_dispatch: {}

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Authorization: Bearer ${ADMIN_TOKEN}" https://actions-public-oidc.depot.dev/-/generate-key
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
