name: rotate-keys
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 1,15 * *' # 12:00 on the 1st and 15th of every month

jobs:
  rotate-keys:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Authorization: Bearer ${ADMIN_TOKEN}" https://actions-public-oidc.depot.dev/-/generate-key
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
